name: test

on:
  push:
  pull_request:
    types: [opened, synchronize]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup PHP, with composer and extensions
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: latest
          coverage: xdebug
      - name: Install Composer dependencies
        run: composer install -q
      - name: Test
        run: vendor/bin/phpunit
      - name: Code Coverage
        uses: qltysh/qlty-action/coverage@08a0a862c159eae9b9003081da6663d96efef637 # v2.3.0
        with:
          oidc: true
          files: build/logs/clover.xml
